// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANErQfhPVu6P8HDYReQ4y7WMS5MGs__Gs',
    appId: '1:104032404853:web:addb73eca25611783cbf3c',
    messagingSenderId: '104032404853',
    projectId: 'selfprojects-eaae3',
    authDomain: 'selfprojects-eaae3.firebaseapp.com',
    storageBucket: 'selfprojects-eaae3.appspot.com',
    measurementId: 'G-CLN8C4G07H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp8cbZ4591MSMtwIORQy8l9QQd9UMv0lY',
    appId: '1:104032404853:android:3f00acb49072af6b3cbf3c',
    messagingSenderId: '104032404853',
    projectId: 'selfprojects-eaae3',
    storageBucket: 'selfprojects-eaae3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC02K1o72W3wYePvo4mB9_Ib7bWt89ThVo',
    appId: '1:104032404853:ios:cf29bb14f1528d2d3cbf3c',
    messagingSenderId: '104032404853',
    projectId: 'selfprojects-eaae3',
    storageBucket: 'selfprojects-eaae3.appspot.com',
    iosBundleId: 'com.example.employeeDtlApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC02K1o72W3wYePvo4mB9_Ib7bWt89ThVo',
    appId: '1:104032404853:ios:cf29bb14f1528d2d3cbf3c',
    messagingSenderId: '104032404853',
    projectId: 'selfprojects-eaae3',
    storageBucket: 'selfprojects-eaae3.appspot.com',
    iosBundleId: 'com.example.employeeDtlApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANErQfhPVu6P8HDYReQ4y7WMS5MGs__Gs',
    appId: '1:104032404853:web:ed66a56202dc51cb3cbf3c',
    messagingSenderId: '104032404853',
    projectId: 'selfprojects-eaae3',
    authDomain: 'selfprojects-eaae3.firebaseapp.com',
    storageBucket: 'selfprojects-eaae3.appspot.com',
    measurementId: 'G-08M7WYQZRZ',
  );
}
